name: Build HomeStore APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Sign APK (The Secret Sauce)
        # هذه الخطوة تقوم بتنزيل أداة التوقيع وتوقيع الملف تلقائياً بمفتاح تصحيح احترافي
        run: |
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar
          java -jar uber-apk-signer-1.3.0.jar --apks app/build/outputs/apk/debug/*.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: HomeStore-App-Signed
          path: app/build/outputs/apk/debug/*-aligned-debugSigned.apk
